Layout/ExtraSpacing:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RescueModifier:
  Enabled: false
