desc 'Build gem'
task :build do
  system('gem build heroku_deploy.gemspec')
end

desc 'Install gem'
task :install do
  system('gem build heroku_deploy.gemspec')
  system('gem install heroku_deploy-*.gem')
end
