#!/usr/bin/env bash

dotfiles_dir="${0%/scripts/dotfiles/dotfiles}"

cd "$dotfiles_dir" || exit 1

case "$1" in
  install)
    make install
    ;;
  uninstall)
    make uninstall
    ;;
  *)
    echo "usage: $(basename "$0") [install|uninstall]"
    exit 1
    ;;
esac
