#!/usr/bin/env ruby

require_relative 'lib/utils'

def update_main
  git(
    'stash',
    'checkout main',
    'pull --rebase'
  )
end

def update_branch(branch)
  git(
    "checkout #{branch}",
    'rebase main',
    "push origin #{branch}:#{branch} --force-with-lease"
  )
end

def merge_branch_into_main(branch)
  git(
    'checkout main',
    "merge --ff-only #{branch}"
  )
end

def push_main(dry_run: false)
  if dry_run
    git('push origin main:main --dry-run')
  else
    git('push origin main:main')
  end
end

def delete_branch(branch)
  git(
    "push origin :#{branch}",
    "branch -D #{branch}"
  )
end

error('Not a git repository.') unless git_repo?

branch = git_branch

if branch == 'main'
  error('Cannot merge main into main.')
end

update_main
update_branch(branch)
merge_branch_into_main(branch)
push_main
delete_branch(branch)
