#!/usr/bin/env ruby

require_relative 'lib/utils'

error('Not a git repository.') unless git_repo?

system('git fetch --all --prune')
puts

remotes = `git remote`.split("\n")

remotes.each do |remote|
  origin_master = 'origin/master'
  remote_master = "#{remote}/master"
  git_log = 'git --no-pager log --pretty="%h %s" '
  commits = `#{git_log} #{origin_master}...#{remote_master}`.split("\n")

  if commits.empty?
    puts('✓'.green + " #{remote_master}")
  else
    puts('☓'.red + " #{remote_master} not synced with #{origin_master} by #{commits.length} commit(s)")
    commits.each do |commit|
      hash, message = commit.split(' ', 2)
      puts('  * ' + hash.yellow + ' ' + message.slice(0, 50))
    end
  end
end
