#!/usr/bin/env ruby

require_relative 'lib/utils'

error('Not a git repository.') unless git_repo?

branch = git_branch

error('Cannot rebase master into master.') if git_branch == 'master'

git('stash', 'checkout master', 'pull --rebase')
git("checkout #{branch}", 'rebase master')
