#!/usr/bin/env ruby

require 'open3'

def brew_uninstall(formula)
  command = "brew uninstall #{formula}"
  stdout, stderr, status = Open3.capture3(command)

  if status.exitstatus == 0
    puts stdout
  else
    case stderr
    when /no such keg/i
      return
    when /refusing to uninstall/i
      puts stderr.split("\n").first
    else
      puts stderr
    end
  end
end

def main
  formula = ARGV.first
  formula_deps = `brew deps #{formula}`.split("\n")

  brew_uninstall(formula)

  formula_deps.each do |formula_dep|
    brew_uninstall(formula_dep)
  end
end

main
