#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

def system!(command)
  system(command) || fail(command)
end

def which?(program)
  `which #{program}`.empty?
end

system('xcode-select --install')

if which?('brew')
  system! %(
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  )
end

system!('brew update')

if which?('brew bundle')
  system!('brew tap Homebrew/bundle')
end

brewfile = File.join(File.dirname(__FILE__), 'Brewfile')

system!("brew bundle --file=#{brewfile}")

code_dir = File.join(File.expand_path('~'), 'Code')

mkdir_p(code_dir)
cd(code_dir)

unless Dir.exists?('dotfiles')
  system!('git clone git@github.com:hachibu/dotfiles.git')
  cd('dotfiles')
  system!('make install')
end
