# Casks
cask_args appdir: '/Applications'

tap 'caskroom/homebrew-cask'
tap 'caskroom/fonts'

cask '1password'
cask 'dropbox'
cask 'firefox'
cask 'font-iosevka'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'spotify'
cask 'vlc'

# Shells
brew 'bash'
brew 'zsh'

# Languages
brew 'crystal-lang'
brew 'node'
brew 'rbenv'

# Databases
brew 'redis'

# Tools
brew 'daemontools'
brew 'git'
brew 'jq'
brew 'openssl'
brew 'shellcheck'
brew 'stow'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'yarn'
brew 'z'
