#!/usr/bin/env ruby

require 'colorize'
require_relative './lib/mock_csv'

if ARGV.empty?
  abort "Error: Missing arguments".red
end

begin
  csv = MockCsv.new(ARGV)
  puts csv.headers
  puts csv.rows(10)
rescue MockCsvError => e
  puts "Error: #{e.message}".red
end
