#!/usr/bin/env ruby

# brew install gnumeric

require 'csv'
require 'date'

def system!(command)
  system(command) || fail(command)
end

def date_range(days)
  (0...days).map { |n| (Date.today - n).to_s }
end

def download(days:, directory:)
  date_range(days).map do |date|
    url = "https://ch-webext.sanleandro.org/coslintranet/PD/calls/#{date}.xls"
    yield url if block_given?
    system!("wget -q -N --directory-prefix=#{directory} #{url}")
  end
end

def convert(files:)
  files.each do |xls|
    csv = xls.sub('.xls', '.csv')
    yield xls, csv if block_given?
    next if File.exist?(csv)
    system!("ssconvert #{xls} #{csv}")
  end
end

def merge(files:, output:)
  headers = %w(callnumber logdate incident inctype address dispo narrative)
  CSV.open(output,'w') do |csv|
    csv << headers
    files.each do |file|
      yield file if block_given?
      CSV.foreach(file, headers: true) { |row| csv << row.values_at(*headers) }
    end
  end
end

if $PROGRAM_NAME == __FILE__
  dir = 'slpd_logs'

  download(days: 7, directory: dir) do |url|
    puts "downloading #{url}"
  end

  convert(files: Dir["#{dir}/*.xls"]) do |xls, csv|
    puts "converting #{xls} #{csv}"
  end

  merge(files: Dir["#{dir}/*.csv"], output: "#{dir}.csv") do |csv|
    puts "merging #{csv}"
  end
end
