#!/usr/bin/env bash

DAYS="${1:-0}"
DAYS_AGO="-${DAYS}d"
DATE=$(date -v "$DAYS_AGO" "+%Y-%m-%d")
SRC="hachibu@blue-demon-local:/home/hachibu/Code/ipcam/media/$DATE/"
DEST="$DATE/"

rsync -rvhP "$SRC" "$DEST"
