#!/usr/bin/env ruby
#
def system!(command)
  system(command) || abort
end

branch = `git symbolic-ref HEAD --short`.strip
remote = ARGV.first&.strip

unless remote
  abort('Error: missing remote argument')
end

git_push_flags = []

if remote == 'staging'
  git_push_flags << '--force'
end

if remote != 'staging' && branch != 'master'
  abort("Error: deployment to #{remote}/master is only allowed from master")
end

puts "git push #{git_push_flags.join(' ')}#{remote} #{branch}:master"
# system!("git push #{git_push_flags.join(' ')} #{remote} #{branch}:master")
# heroku run rake db:migrate --remote heroku
puts "heroku restart --remote #{remote}"
# system!("heroku restart --remote #{remote}")
